### PR TITLE
Navigator/skeleton

### PR DESCRIPTION
**Pull request by TamakiSakura**
I fix the dependencies problem. But for some reason I mess up with the genfiles.properties, I guess that's the reason why it sad it can't merge :(

Is it a good idea to remove this file out of the version control? It doesn't make much sence to commit a generated file.

### CODE REVIEW

**Comment by jim-parry** [comment]
It probably makes sense to exclude this file.
We can't exclude nbproject, however, as there are other files (and folders) there that we do need to keep & share.

**Comment by TamakiSakura** [comment]
Excluding genfiles.properties is just what i want to do....What's the best way of doing this?

**Comment by jim-parry** [comment]
"git ignore" it, and re-push your branch. That update the pull request, maybe even making it mergeable :)

**Comment by TamakiSakura** [comment]
OK I think it should work now....and it compiles also.

**Pull request merged**
